<?xml version="1.0" encoding="UTF-8"?>
<robot generated="20150916 10:40:37.913" generator="Robot 2.9 (Python 2.7.10 on win32)">
<suite source="O:\BusinessSupport\QA_Automation\Testing\Isabella\MyWFG\Resources\Calculator.robot" id="s1" name="Calculator">
<test id="s1-t1" name="Addition">
<kw name="Given calculator has been cleared">
<kw name="Push button">
<arguments>
<arg>C</arg>
</arguments>
<msg timestamp="20150916 10:40:37.976" level="FAIL">No keyword with name 'Push button' found.</msg>
<status status="FAIL" endtime="20150916 10:40:37.976" starttime="20150916 10:40:37.976"></status>
</kw>
<status status="FAIL" endtime="20150916 10:40:37.976" starttime="20150916 10:40:37.974"></status>
</kw>
<status status="FAIL" endtime="20150916 10:40:37.976" critical="yes" starttime="20150916 10:40:37.973">No keyword with name 'Push button' found.</status>
</test>
<status status="FAIL" endtime="20150916 10:40:37.976" starttime="20150916 10:40:37.919"></status>
</suite>
<statistics>
<total>
<stat fail="1" pass="0">Critical Tests</stat>
<stat fail="1" pass="0">All Tests</stat>
</total>
<tag>
</tag>
<suite>
<stat fail="1" id="s1" name="Calculator" pass="0">Calculator</stat>
</suite>
</statistics>
<errors>
<msg timestamp="20150916 10:40:37.972" level="ERROR">Error in file 'O:\BusinessSupport\QA_Automation\Testing\Isabella\MyWFG\Resources\Calculator.robot': Importing test library 'CalculatorLibrary' failed: ImportError: No module named CalculatorLibrary
Traceback (most recent call last):
  None
PYTHONPATH:
  c:\Python27\lib\site-packages\setuptools-18.0.1-py2.7.egg
  C:\PYTHON27
  C:\PYTHON27\DLLs
  C:\PYTHON27\LIB
  C:\PYTHON27\LIB\LIB-TK
  C:\Users\ifayner\Downloads\solution\TravelingTony
  C:\WINDOWS\system32\python27.zip
  c:\Python27\lib\plat-win
  c:\Python27\lib\site-packages</msg>
</errors>
</robot>
